# Default values for hermes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  istio:
    sidecar:
      inject: false
hermes:
  name: hermes

image:
  repository: jgomezselles/hermes
  tag: 0.0.1
  pullPolicy: IfNotPresent

script:
  cm: traffic-script-cm

service:
  type: ClusterIP
  port: 80
