apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serverMock.name }}
  labels:
    {{- include "example-hermes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.serverMock.replicaCount }}
  selector:
    matchLabels:
      {{- include "example-hermes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "example-hermes.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: server-mock
          image: "{{ .Values.serverMock.image.repository }}:{{ .Values.serverMock.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.serverMock.image.pullPolicy }}
          ports:
            - name: http2-rest
              containerPort: {{ .Values.serverMock.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.serverMock.resources | nindent 12 }}

