apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serverMock.name }}
  labels:
    {{- include "example-hermes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serverMock.service.type }}
  ports:
    - port: {{ .Values.serverMock.service.port }}
      targetPort: {{ .Values.serverMock.service.port }}
      protocol: TCP
      name: http2-rest
  selector:
    {{- include "example-hermes.selectorLabels" . | nindent 4 }}
