{
 "title": "Hermes dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "request_id", "query": { "query": "label_values(id)" } }
  ]
 },
 "panels": [
  {
   "title": "Success ratio (last)",
   "type": "gauge",
   "description": "Shows the percentage of requests that were answered with expected result codes",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hermes_responses_rcv_ok{id=~\"$request_id\"}) / sum(hermes_requests_sent{id=~\"$request_id\"}) *100"
    }
   ]
  },
  {
   "title": "Requests sent/s (last)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(hermes_requests_sent{id=~\"$request_id\"}))"
    }
   ]
  },
  {
   "title": "Timeouts/s (last)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(hermes_timeouts{id=~\"$request_id\"}))"
    }
   ]
  },
  {
   "title": "Success ratio (avg)",
   "type": "gauge",
   "description": "Shows the percentage of requests that were answered with expected result codes",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(hermes_responses_rcv_ok{id=~\"$request_id\"}) / sum(hermes_requests_sent{id=~\"$request_id\"}) *100"
    }
   ]
  },
  {
   "title": "Requests sent/s (avg)",
   "type": "stat",
   "description": "Average requests sent per second over the area of visualization",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sum(hermes_requests_sent{id=~\"$request_id\"}))"
    }
   ]
  },
  {
   "title": "Timeouts (avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sum(hermes_timeouts{id=~\"$request_id\"}))"
    }
   ]
  },
  {
   "title": "Responses received/s (last)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(hermes_responses_rcv_ok{id=~\"$request_id\"}))"
    }
   ]
  },
  {
   "title": "Errors (last)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(hermes_resonses_rcv_err{id=~\"$request_id\"}))"
    }
   ]
  },
  {
   "title": "Responses received/s (avg)",
   "type": "stat",
   "description": "Average responses received per second over the area of visualization",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sum(hermes_responses_rcv_ok{id=~\"$request_id\"}))"
    }
   ]
  },
  {
   "title": "Errors (avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sum(hermes_resonses_rcv_err{id=~\"$request_id\"}))"
    }
   ]
  },
  {
   "title": "RT (last)",
   "type": "stat",
   "description": "This gauge shows the latest average of response times in ms of all requests sent by hermes. Only those of expected result codes received are accounted here.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hermes_response_time_ok_ms_sum{id=~\"$request_id\"}[1m] / hermes_response_time_ok_ms_count{id=~\"$request_id\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RT (avg)",
   "type": "stat",
   "description": "This gauge shows the average of response times in ms of all requests sent by hermes over the area of visualization. Only those of expected result codes received are accounted here.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(hermes_response_time_ok_ms_sum{id=~\"$request_id\"}[1m] / hermes_response_time_ok_ms_count{id=~\"$request_id\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response times (ms)",
   "type": "timeseries",
   "description": "This panel shows the response times in ms of all requests sent by hermes. Only those of expected result codes received are accounted here.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hermes_response_time_ok_ms_sum{id=~\"$request_id\"}[1m] / hermes_response_time_ok_ms_count{id=~\"$request_id\"}[1m]",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}