name: Unit tests
on: [push]
jobs:
  build:
    name: Compile and run unit tests
    runs-on: ubuntu-latest
    container:
      image: jgomezselles/hermes_base:0.0.1
      options: "--entrypoint sh"
    steps:
    - uses: actions/checkout@v2

    - run: cmake . -B build
    - run: make -j -C build
    - run: ./build/ut/unit-test